const facility = {
  APP: 'Aproximación',
  CTR: 'Centro',
  DEL: 'Autorización',
  DEP: 'Salidas',
  FSS: 'FIR',
  GND: 'Terrestre',
  TWR: 'Torre',
};

const stations = {
  MMAA: 'Acapulco',
  MMAN: 'Del Norte',
  MMAS: 'Aguascalientes',
  MMBT: 'Huatulco',
  MMCB: 'Cuernavaca',
  MMCE: 'Ciudad del Carmen',
  MMCL: 'Culiacán',
  MMCM: 'Chetumal',
  MMCN: 'Obregón',
  MMCP: 'Campeche',
  MMCS: 'Juárez',
  MMCT: 'Chichen Itzá',
  MMCU: 'Chihuahua',
  MMCV: 'Victoria',
  MMCZ: 'Cozumel',
  MMDO: 'Durango',
  MMEP: 'Tepic',
  MMES: 'Ensenada',
  MMEX: 'México',
  MMFR: 'México',
  MMGA: 'Creel',
  MMGL: 'Guadalajara',
  MMGM: 'Guaymas',
  MMHO: 'Hermosillo',
  MMIA: 'Colima',
  MMID: 'Mérida',
  MMIO: 'Saltillo',
  MMLM: 'Los Mochis',
  MMLO: 'León',
  MMLP: 'La Paz',
  MMLT: 'Loreto',
  MMMA: 'Matamoros',
  MMMD: 'Mérida',
  MMML: 'Mexicali',
  MMMM: 'Morelia',
  MMMT: 'Minatitlán',
  MMMV: 'Monclova',
  MMMX: 'México',
  MMMY: 'Monterrey',
  MMMZ: 'Mazatlán',
  MMNL: 'Nuevo Laredo',
  MMOX: 'Oaxaca',
  MMPA: 'Poza Rica',
  MMPB: 'Puebla',
  MMPE: 'Peñasco',
  MMPG: 'Piedras Negras',
  MMPN: 'Uruapan',
  MMPQ: 'Palenque',
  MMPR: 'Vallarta',
  MMPS: 'Escondido',
  MMQT: 'Querétaro',
  MMRX: 'Reynosa',
  MMSD: 'Cabos',
  MMSL: 'San Lucas',
  MMSM: 'Santa Lucía',
  MMSP: 'San Luis Potosí',
  MMTC: 'Torreón',
  MMTG: 'Tuxla Gutiérrez',
  MMTJ: 'Tijuana',
  MMTL: 'Tulum',
  MMTM: 'Tampico',
  MMTN: 'Tamuín',
  MMTO: 'Toluca',
  MMTP: 'Tapachula',
  MMTY: 'Monterrey',
  MMUN: 'Cancún',
  MMVA: 'Villahermosa',
  MMVR: 'Veracruz',
  MMZC: 'Zacatecas',
  MMZH: 'Zihuatanejo',
  MMZO: 'Manzanillo',
  MMZT: 'Mazatlán',
};

const icaoToText = (icao) => stations[icao];
const callsignToText = (callsign) => {
  const facilityName = facility[callsign.slice(-3)];
  const stationName = stations[callsign.slice(0, 4)];

  return `${facilityName} ${stationName}`;
};

module.exports = { icaoToText, callsignToText };
